// Generated by gencpp from file crimson_msgs/Trans.msg
// DO NOT EDIT!


#ifndef CRIMSON_MSGS_MESSAGE_TRANS_H
#define CRIMSON_MSGS_MESSAGE_TRANS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace crimson_msgs
{
template <class ContainerAllocator>
struct Trans_
{
  typedef Trans_<ContainerAllocator> Type;

  Trans_()
    : header()
    , cfg(0)
    , mode(0)
    , w(0)
    , h(0)  {
    }
  Trans_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cfg(0)
    , mode(0)
    , w(0)
    , h(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _cfg_type;
  _cfg_type cfg;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _w_type;
  _w_type w;

   typedef uint8_t _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::crimson_msgs::Trans_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crimson_msgs::Trans_<ContainerAllocator> const> ConstPtr;

}; // struct Trans_

typedef ::crimson_msgs::Trans_<std::allocator<void> > Trans;

typedef boost::shared_ptr< ::crimson_msgs::Trans > TransPtr;
typedef boost::shared_ptr< ::crimson_msgs::Trans const> TransConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crimson_msgs::Trans_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crimson_msgs::Trans_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crimson_msgs::Trans_<ContainerAllocator1> & lhs, const ::crimson_msgs::Trans_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cfg == rhs.cfg &&
    lhs.mode == rhs.mode &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crimson_msgs::Trans_<ContainerAllocator1> & lhs, const ::crimson_msgs::Trans_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crimson_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crimson_msgs::Trans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crimson_msgs::Trans_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crimson_msgs::Trans_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crimson_msgs::Trans_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crimson_msgs::Trans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crimson_msgs::Trans_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crimson_msgs::Trans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d65fd4aac30cea01cf5e8df196f077b";
  }

  static const char* value(const ::crimson_msgs::Trans_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d65fd4aac30cea0ULL;
  static const uint64_t static_value2 = 0x1cf5e8df196f077bULL;
};

template<class ContainerAllocator>
struct DataType< ::crimson_msgs::Trans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crimson_msgs/Trans";
  }

  static const char* value(const ::crimson_msgs::Trans_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crimson_msgs::Trans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 cfg\n"
"uint8 mode\n"
"uint8 w\n"
"uint8 h\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::crimson_msgs::Trans_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crimson_msgs::Trans_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cfg);
      stream.next(m.mode);
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trans_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crimson_msgs::Trans_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crimson_msgs::Trans_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cfg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cfg);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "w: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRIMSON_MSGS_MESSAGE_TRANS_H
